[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_pot = "2g2gLFwXCdbYeZotkH6MxnFnccJVN5ChHHZLk9enNLzi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://api.mainnet-beta.solana.com"
wallet = "./backpack-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
